### ISSUE TITLE
Implement custom dataset Schema

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#1]
In CKAN, the dataset schema lists the metadata fields present in [a dataset and resources](https://www.opendatani.gov.uk/api/action/package_show?id=notifiable-infectious-diseases-report-2016-week-17), as well as the validation rules attached to them. CKAN includes a [default schema](https://github.com/ckan/ckan/blob/master/ckan/logic/schema.py#L103) but most instances will customize it to suit their own needs.

This was traditionally done with the `IDatasetForm` interface, and it involved a fairly [tedious process](http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html). Luckily now there is [ckanext-scheming](https://github.com/ckan/ckanext-scheming) available. ckanext-scheming allows to define one or more custom schemas declaratively using a JSON file like [this one](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/schemas/dataset.json). The extension will then take care of creating any internal hooks on `IDatasetForm` and rendering the form depending on the definitions.

We might need to end up using `IDatasetForm` anyway if we need more flexibility but to start with let's try to stick with ckanext-scheming.

I already added the [schema definition file](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/schemas/dataset.json) to this repo, which includes one of the custom fields (Data Processing Status), now we need to add the rest defined in the [Dataset Field Spec sheet](https://docs.google.com/spreadsheets/d/1Gg1lNXqZG_CBltv6hcRX6UkTmOTZdJ4MtwxmXQjY0Fk/edit#gid=90335564) and [File Field Spec sheet](https://docs.google.com/spreadsheets/d/1Gg1lNXqZG_CBltv6hcRX6UkTmOTZdJ4MtwxmXQjY0Fk/edit#gid=228295987) on the spreadsheet.

Many fields in the spec need to be clarified with the client. I added a couple of columns with comments about the status of each. We will update them as we get more details, but the ones marked `ok` and `done` are safe to add.

Tasks:

- [x] Edit the `dataset.json` file to add any existing core field and new fields needed
  * If custom validators are needed, register them with `IValidators` (example [here](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/plugin.py#L231) and [here](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/validators.py#L11))
  * If custom field types or template snippets are needed, create custom presets like [here](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/examples/ckan_default_schema.json#L110) and [here](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/presets.json)

Dataset:
- [x] Date range data collected -> #11
- [x] Date file created -> internal
- [x] Date modified -> internal
- [x] Linked datasets -> #7 
- [x] Keywords
- [x] Unit of measurement
- [x] Description
- [x] Operational purpose of data
- [x] Uploader -> internal
- [x] HXL-ated?
- [x] Raw Data Access Level
- [x] Dataset process status -> #8 
- [x] Project URL
- [x] Archive status
- [x] Identifiability -> #9 
- [x] Admin Notes -> #10 
- [x] File Attachments
- [x] Original ID
- [x] Data collection technique
- [x] License dataset

Resource:

- [x] Date range data collected -> #11 
- [x] Version
- [x] Date modified -> internal
- [x] File Type
- [x] Description
- [x] Created by -> internal
- [x] File format
- [x] HXL-ated?
- [x] File process status
- [x] Identifiability -> #9 
- [x] File Size -> internal

**Comment by roll** [comment]
@amercader 
So if I've got it right I'm going to start to work on it from tomorrow.
