### ISSUE TITLE
Update curation implementation based on the client feedback

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#100]
# Overview

Prepare a document to gather feedback and info.

# Tasks

- [ ] document to gather feedback
- [ ] update states naming (submitted?)
- [ ] remove curation stream after publication for some actors?
- [ ] update all help texts based on new copies
- [ ] TBD
