### ISSUE TITLE
Make data collector a free text field (handle DDI import)

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#200]
# Overview

From Mariann:

> it seems one of the livelihoods datasets (trying to figure out which) imported from DDI had two values for the data collector field: one was UNHCR, the other was the Jordan River Foundation, which does not exist in RIDL.
> It seems the DDI was imported successfully with only UNHCR as data collector. 

IIRC this was handled correctly but maybe there is a regression. Or maybe the data collector id is not one of the ones allowed

Example provided:

https://ridl.unhcr.org/dataset/unhcr-jor-2017-lis-1-1

# Tasks

- [ ] convert the field to a `free text`
- [ ] use autocomplete widget?
- [ ] handle multiple values 
- [ ] create a migration script

**Comment by amercader** [comment]
This is likely caused by one the values not being part of the required ones in the schema. We discussed options with UNHCR, including adding a a free text field for data collectors not part of the default list.

**Comment by roll** [comment]
Decided to make the field a free text one

**Comment by amercader** [comment]
@roll to index a field as multivalued:

1. On `before_index` add the `vocab_data_collector` to the package dict (all `vocab_*` fields get indexed as multivalue)
2. Update the `*_facets` method to use `vocab_data_collector` instead of the current one

This assumes that the values are returned as a list in the dataset dict. To ensure so add a validator in the `output_validators` that parses the stored value
