### ISSUE TITLE
Rebase on ckanext-cloudstorage with addition of S3 stack

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#241]
# Overview

For now, the AWS setup:
- lose all the resource's files on every deployment (the files we have uploaded)

# Tasks
- [x] ~~Fork and update ckanext-cloudstorage to include patches to work on CKAN 2.8 (at least [this one](https://github.com/TkTech/ckanext-cloudstorage/pull/35)~~ Not needed as the PR has been merged
- [x] Install and configure [`ckanext-cloudstorage`](https://github.com/TkTech/ckanext-cloudstorage) in the Docker image (it requires a key pair, check the [docs](https://github.com/TkTech/ckanext-cloudstorage#setup) for config options
- [x] Modify the CDK scripts if necessary to create the bucket if it not exists, get keys etc (this might already been done)
- [x] Run the [migration script](https://github.com/TkTech/ckanext-cloudstorage#migrating-from-filestorage) to move the file hosted locally in the UNHCR infra to the S3 bucket (this needs to be done in the RIDL server, so via the VPN) - #256 #257
- [ ] Make it work

The file structure for local uploads is the following, for a site with a dataset with two resources (with ids `769e600a-c657-4d1b-9b93-ea10490ecd2b` and `3475d320-edda-4207-80d3-b29b84273f88`) and an image for an org (`myorg.png`)

```
storage_dir
├── resources
│   ├── 347
│   │   └── 5d3
│   │       └── 20-edda-4207-80d3-b29b84273f88
│   └── 769
│       └── e60
│           └── 0a-c657-4d1b-9b93-ea10490ecd2b
├── storage
    └── uploads
        └── group
            └── 2020-01-08-105647.644569myorg.png
```

I don't think we need to worry about the `storage` folder at all, but I'll check once we get access to the servers again.

Cloudstorage uses the following structure: 

```
bucket
├── resources
    └── <resource_id>
        └── <munged_file_name>
```
The file name is stored in the `url` field for local uploads.

**Comment by TkTech** [comment]
It's been awhile, but that file structure looks like the plain ol' CKAN on-disk structure. If that's the case, once you have ckanext-cloudstorage configured you can just run migrate: https://github.com/TkTech/ckanext-cloudstorage#migrating-from-filestorage.

**Comment by amercader** [comment]
Your absolutely right @TkTech, that saves us some time! Thanks a lot.

**Comment by roll** [comment]
@amercader @TkTech 

I've run into:
```
LibcloudError: <LibcloudError in <class 'libcloud.storage.drivers.s3.S3StorageDriver'> 'This bucket is located in a different region. Please use the correct driver.'>
```
Although it seems the region is the same. I'm going to re-check permissions but maybe I have some advice of the top of your head

**Comment by roll** [comment]
I've tested locally:

```
aws s3 cp ~/valid.csv s3://ridl-uat/ --profile ridl-aws
upload: ../../valid.csv to s3://ridl-uat/valid.csv # success
```

where the `ridl-aws` profile was constructed from the public/secret key from `CKANEXT__CLOUDSTORAGE__DRIVER_OPTIONS`

**Comment by TkTech** [comment]
In the newer versions of libcloud you pass a region to the driver constructor. In the older v1.5 that ckanext-cloudstorage still uses you instead do it by passing an explicit provider for your region. If I had to take a guess without seeing your configuration you're probably using the `S3` driver rather than the `S3_EU_WEST` (or wherever your data is stored) driver.

**Comment by roll** [comment]
Hi @TkTech @amercader,

I was able to set up everything to successfully:
- upload data files as resource
- see them in the S3 bucket
- download from the S3 bucket and verify contents 

The only problem is remaining:
- clicking on `download` leads to a server error

```

16:01:13
Error - <type 'exceptions.AttributeError'>: 'ResourceCloudStorage' object has no attribute 'get_path'

16:01:13
URL: https://ridl-uat.openknowledge.io/dataset/b16563f1-1224-4be4-a2e6-8b6625e24069/resource/7cc4909d-715f-473d-9663-c10a812e51dc/download/valid.csv

16:01:13
File '/usr/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__

16:01:13
app_iter = self.application(environ, sr_checker)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__

16:01:13
resp = self.call_func(req, *args, **self.kwargs)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func

16:01:13
return self.func(req, *args, **kwargs)

16:01:13
File '/usr/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__

16:01:13
return request.get_response(self.app)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response

16:01:13
application, catch_exc_info=False)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application

16:01:13
app_iter = application(self.environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__

16:01:13
resp = self.call_func(req, *args, **self.kwargs)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func

16:01:13
return self.func(req, *args, **kwargs)

16:01:13
File '/usr/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__

16:01:13
response = request.get_response(self.app)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response

16:01:13
application, catch_exc_info=False)

16:01:13
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application

16:01:13
app_iter = application(self.environ, start_response)

16:01:13
File '/srv/app/src/ckan/ckan/config/middleware/pylons_app.py', line 265 in inner

16:01:13
result = application(environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__

16:01:13
return self.app(environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__

16:01:13
return self.wrap_app(environ, session_start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__

16:01:13
response = self.app(environ, start_response)

16:01:13
File '/srv/app/src/ckan/ckan/config/middleware/common_middleware.py', line 30 in __call__

16:01:13
return self.app(environ, start_response)

16:01:13
File '/srv/app/src/ckan/ckan/config/middleware/common_middleware.py', line 56 in __call__

16:01:13
return self.app(environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__

16:01:13
response = self.dispatch(controller, environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch

16:01:13
return controller(environ, start_response)

16:01:13
File '/srv/app/src/ckan/ckan/lib/base.py', line 240 in __call__

16:01:13
res = WSGIController.__call__(self, environ, start_response)

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__

16:01:13
response = self._dispatch_call()

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call

16:01:13
response = self._inspect_call(func)

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call

16:01:13
result = self._perform_call(func, args)

16:01:13
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call

16:01:13
return func(**args)

16:01:13
File '/srv/app/src/ckanext-unhcr/ckanext/unhcr/controllers/extended_package.py', line 120 in resource_download

16:01:13
id, resource_id, filename=filename)

16:01:13
File '/srv/app/src/ckan/ckan/controllers/package.py', line 1167 in resource_download

16:01:13
filepath = upload.get_path(rsc['id'])

16:01:13
AttributeError: 'ResourceCloudStorage' object has no attribute 'get_path'
```

**Comment by roll** [comment]
The current S3 bucket settings are:
```
    this.bucket = new s3.Bucket(this, 'bucket', {
      bucketName: `ridl-${props.envName}`,
      removalPolicy:
        props.envName === 'prod' ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      // The ckanext-cloudstorage extension doens't work with the option below
      // encryption: s3.BucketEncryption.KMS,
    })
```
Can you advice if I need to add some additional configuration to the bucket?

**Comment by TkTech** [comment]
Your traceback is hard to read, but it looks like you're somehow still using the default, CKAN `resource_download`. ckanext-cloudstorage [replaces](https://github.com/TkTech/ckanext-cloudstorage/blob/master/ckanext/cloudstorage/plugin.py#L66) these routes with [its own](https://github.com/TkTech/ckanext-cloudstorage/blob/master/ckanext/cloudstorage/controller.py#L13) so it can correct headers and ensure URLs are signed if enabled.

**Comment by roll** [comment]
@TkTech 
Sorry for the format and thanks for the help. The problem was exactly what you described :+1:
