### ISSUE TITLE
Resource-level visibility

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#581]
### Context

In a standard CKAN install, a dataset visibility is defined by the `private` metadata field (a boolean). A **private** dataset can only be accessed by members of its organization, collaborators or sysadmins. This includes seeing the metadata and downloading the data (for members) and editing the metadata (for editors and admins). A **public** dataset can be accessed and its resources downloaded by any user.

RIDL had a requirement to introduce a third state: metadata public but private data. That means that all users should be able to see all datasets metadata (ie browse and access dataset pages), but in some cases *downloading* the files should be only available to data container members or collaborators. In RIDL this are called "Private" datasets, and when visiting the dataset page as a user without permissions to download you get a message (and the download links are disabled):

![Screenshot_2021-05-31 United Republic of Tanzania Livelihoods Programme Monitoring Beneficiary Survey - 2020 - RIDL](https://user-images.githubusercontent.com/200230/120177518-d12f5880-c208-11eb-9c3e-201f7eefd2dc.png)

As the builtin `private` field didn't allow a new state, visibility is handled by a custom `visibility` field, defined [here](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/schemas/dataset.json#L61-L78). The builtin [`private`](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/schemas/dataset.json#L54-L60) field is always set to `False` (via the `always_false_if_not_sysadmin` validator).

Note that while there are three theoretically possible cases, only two are available via the frontend:

|  Internal Access Level | `visibility` value | `private` value | notes |
|---|---|---|---|
| Internally visible | `public` | `True` | Metadata visible / Downloads public |
| Private | `restricted` | `True` | Metadata visible / Downloads restricted |
| *{Not show}* | `private` | `False` | Metadata restricted / Downloads restricted (*Not available to normal users*) |

The third one was added in case true private datasets were ever needed but to all intents and purposes, all RIDL datasets have public metadata and some of them restricted downloads.

### Current implementation

As mentioned before, the [`visibility`](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/schemas/dataset.json#L61-L78) field is the one defining whether some dataset files can be downloaded or not. The [`visibility_validator`](https://github.com/okfn/ckanext-unhcr/blob/5743888dee8608dd2754331a8f60c74e13f1349b/ckanext/unhcr/validators.py#L176) ensures that the value is supported and that the builtin `private` field is always `False`.

This field is mostly used in two places:

* In our custom [`resource_download`](https://github.com/okfn/ckanext-unhcr/blob/5743888dee8608dd2754331a8f60c74e13f1349b/ckanext/unhcr/auth.py#L212) auth function (called from the custom [`resource.download`](https://github.com/okfn/ckanext-unhcr/blob/b1152c47119202ee140108e5e43de9cbaa3f1181/ckanext/unhcr/blueprints/resource.py#L26) endpoint)
* In the dataset templates (eg [`read.html`](https://github.com/okfn/ckanext-unhcr/blob/ckan2.9/ckanext/unhcr/templates/package/read.html#L74)) to show the UI elements related to restricted datasets

### Requirements

The new requirements for the visibility field are that rather than applying at the dataset level it should apply at the individual resources level. That means that within an individual dataset some resources should be able to be downloaded publicly while others should remain private (ie only downloadable by data container members and collaborators).

### Implementation

At the schema level, we need to move the `visibility` field from `dataset_fields` to `resource_fields`. This should take care of the forms. We assume that Private is the expected default in resources as well.

This will require a migration. Current "restricted"  datasets will have all their resources updated to have `visibility: restricted`, while all the other datasets / resources should have `visibility: public`. The easiest way to do this is probably via an API script.

At the auth level, `resource_download` should take into account the value of the individual resource `visibility` field rather than the dataset one.

At the template level, notices, icons etc should be moved from the dataset page to the resource page or resource listing, eg:
* Lock icon on the top right of the dataset page should be move to the specific restricted resources.
* The "request access" notice should be shown only in the resource page (note that this is currently broken, see #580)

### TODO

There are some outstanding details that need to be clarified with the client. 

- [ ] We automatically set "Internal Access Level" to private at the dataset level when "Identifiability" is "Personally identifiable". With the new setup, should we enforce that all resources from those datasets are always private? Or should we allow users to choose  on each resource?
- [ ] The dataset schema has an "External Access Level". Are there any implications for it caused by moving "Internal Access Level" to resource?
- [ ] When depositing a dataset, users can choose the default value for "Internal Access Level". (see screenshot below) With the new changes this no longer applies, as this value would refer to resources. Should we just remove the field? Explain it somehow?
- [ ] ~~The same applies to importing a dataset from DDI/XML~~ Update: We actually automatically create the resources for DDI imports so we can apply this value to the generated resources.

![Screenshot_2021-05-31 Data deposit - Data Containers - RIDL](https://user-images.githubusercontent.com/200230/120186369-b6aeac80-c213-11eb-8166-ae45c74219a6.png)

**Comment by chris48s** [comment]
Follow-up:
- Personally identifiable is already a resource-level field. If a resource is identifiable the resource is private. We can keep pulling the "personally identifiable" field up to the dataset to continue using it as a search facet, but it shouldn't make the whole dataset private.
- Retain "external access level" at the dataset level
- Remove internal access level from data deposit modal dialog
- Private field applies to both data files and attachment resources

TODO:
- Where do we display "private" indicator/lock icon?

**Comment by avdata99** [comment]
Question:
 - _The "request access" notice should be shown only in the resource page_ means that we need to [add `resources` to the `object_type` enum](https://github.com/okfn/ckanext-unhcr/blob/581_resources_visibility/ckanext/unhcr/models.py#L47-L48)?
