### ISSUE TITLE
Modifications to the RIDL schema

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#67]
Based on changes on #64 ([schema file](https://github.com/Edouard-Legoupil/ckanext-unhcr/blob/04ea232868a0d5f9f607fb55cea1b8787776ec8e/ckanext/unhcr/schemas/dataset.json)).

- [x] Rename `source_organization` -> `data_collector`
- [x] Make `unit_of_measurement` free text rather than predefined values
- [x]  add field `ddi` | boolean (or equivalent) | yes/no - Required by #69
- [x] Update the predefined values for select fields with values o #64:
  - [x]  `data_collector`
  - [x] `keywords`
  - [x] `data_collection_technique`
  - [x] `operational_purpose_of_data` 
  - [x] `resource.file_type`
- [x] Add new fields (name | type | observation):
  - [x]  `short_title` | text | below `title
  - [x]  `geog_coverage` | text
  - [x]  `sampling_procedure` | multiple_select | values on #64
  - [x]  `sampling_procedure_notes` | markdown | don't index
  - [x]  `response_rate_notes` | markdown | don't index
  - [x]  `data_collection_notes` | markdown | don't index
  - [x]  `weight_notes` | markdown | don't index
  - [x]  `clean_ops_notes` | markdown | don't index
  - [x]  `data_accs_notes` | markdown | don't index
- [x] update field `process_status`/`resource.process_status` (update jobs etc)
- [x] update field `identifiability`/`resource.identifiability` (update jobs etc)
