### ISSUE TITLE
WP04: Data deposit and curation process tracking

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#73]
## Overview

The goal is to provide a mechanism for users to deposit data in the portal that does not currently meet the publication requirements, but that can undergo a curation process to make it ready for being published in RIDL.

The feature will be implemented around a single data container (Curation container), and there will be a team of users assigned to it (Curation team), both editors and administrators.

* Use case 1: A logged-in user (ie UNHCR staff) that doesn't belong to any data container wants to publish some data in RIDL.
* Use case 2: A user belonging to a data container wants to publish some data to a data container they don't belong to.

## Roles

* Data submitter
* Curation editor
* Curation admin
* Data container admin

## Details

1. Any logged-in user in RIDL can create a dataset in the Curation container (even if it belongs to a data container).
2. When creating a dataset in the curation container:
    2.1. The schema used is more flexible that in the default process (eg less fields required).
    2.2. Users can define the data container they would like the dataset to be added to (this can be later overridden by the curation editors)
3. When the dataset is submitted:
    3.1. The Data submitter gets a notification that the dataset has been received and that someone from the curation team will be assigned to it.
    3.2. The Curation admins get a notification that there is a new dataset submitted
4. The curation admin assigns a curation editor to the dataset, who will be the main point of contact with the data submitter.
    4.1. The data submitter gets a notification that user X has been assigned to the dataset, including the user details
    4.2. The curation editor gets a notification regarding their assignment.
5. While the dataset has not been assigned to a curation editor, it can be modified by the data submitter, and they can withdraw the dataset directly (delete it from the curation container).
6. Once a dataset gets assigned to curation editor, the data submitter can no longer edit it or withdraw it. To do so they need to contact the curation editor, who can do these actions.
7. Even though it will have only one curation editor assigned, all curation editors will be able to edit a deposited dataset.
8. Curation admins can change the curation editors assigned to a particular dataset.
9. During the whole time a dataset is in the curation container, only members of the curation team can access it and browse it, as well as the original data submitter.
10. Once the curation editor is happy with the dataset (eg normal validation passes), they can make it public into RIDL.
    10.1. The data submitter is notified that the dataset has been made public.
    10.2. The destination data container admins get notified that a new dataset has been added.
    10.3. The curation admins get notified that the process has finished for that particular dataset.
11. Once the dataset is assigned to its destination data container the original data submitter does not have any rights on it. If needed, they can request to be added to the data container to gain them.

## Main implementation tasks

All these will get detailed issues

- [x] Modify permissions and indexing to implement the curation data container as described above
- [x] Custom schema for datasets created in the triaging data container (eg relaxing mandatory fields and adding extra ones regarding the curation process)
- [x] Implement curation process features (status changes, notifications, etc)
- [x] Logic and UI regarding the curation process
