### ISSUE TITLE
Create a separate schema for curated datasets

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#74]
As curated datasets have a more flexible schema than the default one, it makes sense to handle those as a separate dataset type (`curated-dataset`), and create a proper one when the curation process is finished.

Using a custom type will also hide all curated datasets from the default search listings (but not on `/curated-dataset`, more on that later).

Curated datasets have the same fields as the default schema, but only a minimal subset is required (let's start with title and description for now). Additionally they have an extra field for the data container they should end up in if the curation process finishes (eg `owner_org_dest` or something similar). `owner_org` will always be the id of the Curation Data Container. This will be enforced by a custom validator.

User creates a curated dataset (minimal schema, proposed data container) -> Assigned to the Curation Data Container -> [ Curation process TBD ] -> A new dataset is created on the requested data container

One thing that might be useful is to create a new endpoint that validates the dataset metadata against the default schema but without creating a dataset: you upload the data_dict, validate it against the default schema and return any ValidationErrors found. This will be useful for data curators to know when their data is ready.

## Tasks
- [x]  Create a new `curated-dataset` type in the schemas folder. Same fields as the default but only title and description mandatory.
- [x] Add a new field that holds the suggested data container (we can validate if it's an existing org, there's probably an existing validator in core for that)
- [x] Add a validator on `owner_org` that forces the value to be the Curation Data Container one
- [x] Implement mechanism for creating a regular dataset from a curated one (that meets all the metadata requirements). Whatever works best of:
   1. Use the same dataset, just change the owner_org. This is cleaner but might give permission problems
   2. Create a new dataset in the destination data container (by an internal account) using the same metadata as the curated one, and delete the curated one afterwards.
- [x] Hide curated datasets from search to users that are not members of the curation container (this could be as easy as to create all datasets private, or we might need to use `IPermissionLabels`)
