### ISSUE TITLE
Implement deposit data container permissions

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#75]
The deposit data container is implemented as a normal data container, ie is just a regular organization under the hood, but it does not come up in the data container index. For now it can be manually created, and the curation team (ie this organization admins and editors) can be manually added.

All users should be able to add datasets to the curation data container, but only edit the ones they submitted. We will need to extend the `package_create` and `package_update` auth functions to accommodate this.

The editors and admins in this container should be able to edit all datasets in it (default behaviour). The rest of users should not be able to see what datasets belong to this data container.

## Tasks

- [x] Create Curation Data Container and add some editors and admins
- [x] Modify the authorization logic to implement the spec above
- [x] Restrict access to this data container to non-members (`organization_show` auth function) - MOVED #78

**Comment by roll** [comment]
To take a look on the data container fields:
- Country
- Geographic area referenced
It's required so what values should be for Curation Data Container

**Comment by amercader** [comment]
Maybe we can have a custom data-container (org) type/schema just for the curation data container that doesn't have these constraints

**Comment by roll** [comment]
> Restrict access to this data container to non-members (`organization_show` auth function)

I have created an issue for it - #78 (it makes sense to do it after we implement curating UI because for now we need `Data Deposit` for testing/demostration)
