### ISSUE TITLE
Deposited dataset states and associated permissions

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#77]
We'll add a new field to track the state of deposited datasets. This will affect the permissions of the different roles and track on what stage of the curation process it is.

The overview of the whole process is as follows:

* The data depositor created a new deposited dataset (state = draft)
* They can do further changes, and submit it for curation (state = submitted)
* The curation admin(s) assign an editor to the dataset (state = in_progress)
* If they need the depositor to make changes to the dataset, they unlock it (state = draft)
* Once the depositor has made the changes, they re-submit it (state = in_progress, because there is already an assigned editor)

**Update:**

* Once the editor is happy and validation passes, the dataset is sent back to the depositor for final approval (state = approval_pending)
* The depositor does a final review and accepts the publication (state=published), or rejects it (state=in_progress)

## Tasks

- [x] Add a new custom field name `curation_state` (It's better not to use the default schema `state` as this is hardcoded in too many places). For now, the possible values for this will be :
   * `draft`
   * `submitted`
   * `in_progress`
   * `approval_pending`
   * `published`
  
- [x] Add a validator to ensure that unless the logged in user is member of the curation team, the value is always `draft` (ie default for new deposited datasets).
- [x] When the depositor is happy with the dataset, they can submit it for curation (state changes to `submitted` if there is no curation editor assigned, `in_progress` otherwise). Here's a sample of how it could be displayed:
![screenshot_2019-02-18 testingtitle - u s department of education](https://user-images.githubusercontent.com/200230/52959440-7d313a80-3396-11e9-872e-c4f174781161.png)

- [x] When the curation admin assigns an editor to the dataset the state changes to `in_progress`
- [x] Curation admins and editors can change the state to `draft`, so the depositor can make further changes.
- [x] If the deposited dataset is in `draft` state, only the original depositor can edit it (we can match against the logged in user using `creator_user_id`)
- [x] If the deposited dataset is in `in_progress` state, only admins or editors of the Data Deposit container can edit it
- [x] When validation passes, Editors can request a final review from the original depositor. The depositor can still not edit the dataset, but will be able to publish the dataset or reject it, returning it to the editor
- [x] Datasets with a curation state of `published` have been migrated to the destination data container and changed their types to `dataset` so they inherit whatever normal permissions apply

**Comment by roll** [comment]
> curation team
So for now, I assume that being a member of curation team means:
- belongs to `data-deposit` org
- in role `admin` or `editor`

But we need to find a definition what does it mean to be a regular member of `data-deposit`. Or disable this option.

**Comment by amercader** [comment]
@roll I updated the description to reflect the new approval stage

As for your question about the curation team, yes, it's just members of the `data-deposit` container.
