### ISSUE TITLE
Data Deposit page and curation UI

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#84]
We need an index page that lists all deposited datasets, accessible only to the curation team, where they can filter them by some specific fields.

I think it makes sense to have this separate from the user dashboard tabs in case the number of deposited datasets is very big, and to take advantage of all the faceting, pagination etc.

We have two options for implementing this page

1. The index page for an organization created in the new org type for the deposited datasets (eg `/data-deposit/deposit`)
2. Use the index page for the `deposited-dataset` dataset type, eg `/deposited-dataset`

I don't have a strong preference. It depends on which one is easier to lock down via authorization.

### Tasks

- [ ] Change permissions so only members of the curation team (ie members of the data deposit org) can access this page (related to #78)
- [ ] Point link in the header to this page. Link should be only visible to curators and admins. Move link to the right. Change icon
- [ ] Remove all facets, and include two new ones: Curation stage, and Curator assigned (if possible, if not show Assigned/Unassigned)
- [ ] Remove tabs (activity, etc)
- [ ] Display curation status in the dataset items in the listing, and also the original depositor and the editor assigned (if any)

---

From #81 

Overview of the Data Deposit and curation UI:

Issues prioritized in the milestone: https://github.com/okfn/ckanext-unhcr/milestone/1

* Data Deposit:  It is only accessible to sysadmins and curation team members. All deposited datasets are shown there, and there are filters for stage (draft, submitted, pending approval...) and for who is assigned to the datasets. (See #84).
* Custom deposited dataset page and form. (See #85 and #87).
* Tabs on the user dashboard (See #86)
   * For all users: My deposited datasets
   * For curator admins: Unassigned deposited datasets
   * For curator editors and admins: Deposited datasets assigned to me
* Curation activity stream (TBD)

----

From #81 

Keeping this here for reference:

If a curator approves a private dataset they will be redirected to a 404 page, as they don't have permissions to see private datasets that belong to another data container. After discussion with the client this is fine, we can sort it out at the app level for now, making editors sysadmins.
