### ISSUE TITLE
EPIC: Prepare for CKAN 2.10

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#957]
Create issues to prepare RIDL for CKAN 2.10

Read: https://github.com/ckan/ckan/wiki/CKAN-2.9-to-2.10-migration-tips#test-classes-setup-methods-not-firing-or-firing-in-wrong-order

 - [x] IPackageController hooks #966
 - [x] No builtin functions as validators #967
 - [x] Imports for activity #956 
 - [x] Upgrade all tests #955 
 - [x] Models #968
 - [x] Frontend and templates #969

**Comment by avdata99** [comment]
Errors were found, but these will be covered in new issues.
Closing this one.
