### ISSUE TITLE
Finalize curation implementation

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-unhcr#96]
# Overview

Here is a list of all outstanding issue aside main functionality (see main issues)

# Tasks

- [x] user gets 403 accessing the curation stream
- [x] hide not needed entries in curation stream
- [x] submit message is not in the curation stream
- [x] more prominent messages in curation stream (?)
- [x] ---
- [x] curation UI should show target container for datasets
- [x] if possible make `Data Deposit` header active for all/most curation pages
- [x] use display names for depositors/curators for contacs/filters/etc (?)
- [x] add links to user names in sidebar/dataset-item?
- [x] facet pills use `organization` url instead of data-container -> #99
- [x] Index user display names (depositor and curators), not `name`
- [x] user can't see curator email -> #98 
- [x] ---
- [x] data deposit org creation script
- [x] review `get_data_deposit` usage performance (caching?)
- [x] review/clean dashboard activities?
- [x] user testing of the whole workflow

**Comment by roll** [comment]
@amercader 
I've added everything I've noted by now. 
Let's review after #84 and #82 and other problems here.
